//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coleta()
        {
            this.ProdutosColeta = new HashSet<ProdutosColeta>();
        }
    
        public int id { get; set; }
        public int idMercado { get; set; }
        public int idTipoLista { get; set; }
        public string Data { get; set; }
        public string ResponsavelColeta { get; set; }
        public string ResponsavelMercado { get; set; }
        public string ImgAssinatura { get; set; }
    
        public virtual Lista Lista { get; set; }
        public virtual Mercados Mercados { get; set; }
        public virtual TipoColeta TipoColeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosColeta> ProdutosColeta { get; set; }
    }
}
