//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutosColeta
    {
        public int id { get; set; }
        public int idColeta { get; set; }
        public int idProduto { get; set; }
        public decimal PrecoProduto { get; set; }
        public string Status { get; set; }
    
        public virtual Coleta Coleta { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
