//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produtos()
        {
            this.ProdutosColeta = new HashSet<ProdutosColeta>();
            this.ProdutosLista = new HashSet<ProdutosLista>();
        }
    
        public int id { get; set; }
        public int idSetor { get; set; }
        public Nullable<int> idMarca { get; set; }
        public string Nome { get; set; }
        public string CodigoBarras { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual Setores Setores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosColeta> ProdutosColeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosLista> ProdutosLista { get; set; }
    }
}
